name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1
      - name: Determine version
        run: echo "${{ github.ref }}" | sed -e 's%refs/tags/v%VERSION=%' >> $GITHUB_ENV
      - name: Fill in version
        run: poetry version $VERSION
      - name: Build distribution files
        run: poetry build
      - name: Publish on PyPI
        run: |
          poetry config repositories.pypi https://upload.pypi.org/legacy/
          poetry publish -r pypi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_UPLOAD_TOKEN }}
